// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TechCart.Orders.Infrastructure;

#nullable disable

namespace TechCart.Orders.Infrastructure.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    partial class OrdersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("orders")
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TechCart.Orders.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_number");

                    b.Property<string>("ShippingAddressLine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shipping_address_line");

                    b.Property<string>("ShippingCity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shipping_city");

                    b.Property<string>("ShippingDistrict")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shipping_district");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("numeric")
                        .HasColumnName("shipping_fee");

                    b.Property<string>("ShippingFullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shipping_full_name");

                    b.Property<string>("ShippingPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shipping_phone");

                    b.Property<string>("ShippingPostalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shipping_postal_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<decimal>("VatTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("vat_total");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("orders", "orders");
                });
#pragma warning restore 612, 618
        }
    }
}
