<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\addresses\TechCart.Addresses.Application\TechCart.Addresses.Application.csproj" />
    <ProjectReference Include="..\..\cart_items\TechCart.CartItems.Application\TechCart.CartItems.Application.csproj" />
    <ProjectReference Include="..\..\order_items\TechCart.OrderItems.Application\TechCart.OrderItems.Application.csproj" />
    <ProjectReference Include="..\..\payments\TechCart.Payments.Application\TechCart.Payments.Application.csproj" />
    <ProjectReference Include="..\TechCart.Orders.Contracts\TechCart.Orders.Contracts.csproj" />
    <ProjectReference Include="..\TechCart.Orders.Domain\TechCart.Orders.Domain.csproj" />
    <ProjectReference Include="..\..\cart_items\TechCart.CartItems.Contracts\TechCart.CartItems.Contracts.csproj" />
    <ProjectReference Include="..\..\inventory\TechCart.Inventory.Application\TechCart.Inventory.Application.csproj" />
  </ItemGroup>

</Project>
