<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TechCart.Addresses.Contracts\TechCart.Addresses.Contracts.csproj" />
    <ProjectReference Include="..\TechCart.Addresses.Domain\TechCart.Addresses.Domain.csproj" />
  </ItemGroup>

</Project>
