<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\products\TechCart.Products.Contracts\TechCart.Products.Contracts.csproj" />
    <ProjectReference Include="..\..\products\TechCart.Products.Application\TechCart.Products.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
