<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\product_images\TechCart.ProductImages.Domain\TechCart.ProductImages.Domain.csproj" />
    <ProjectReference Include="..\TechCart.Products.Contracts\TechCart.Products.Contracts.csproj" />
    <ProjectReference Include="..\TechCart.Products.Domain\TechCart.Products.Domain.csproj" />
    <ProjectReference Include="..\..\categories\TechCart.Categories.Application\TechCart.Categories.Application.csproj" />
    <ProjectReference Include="..\..\brands\TechCart.Brands.Application\TechCart.Brands.Application.csproj" />
    <ProjectReference Include="..\..\product_images\TechCart.ProductImages.Application\TechCart.ProductImages.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\TechCart.SharedKernel\TechCart.SharedKernel.csproj" />
  </ItemGroup>

</Project>
