<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TechCart.CartItems.Application\TechCart.CartItems.Application.csproj" />
    <ProjectReference Include="..\TechCart.CartItems.Contracts\TechCart.CartItems.Contracts.csproj" />
    <ProjectReference Include="..\TechCart.CartItems.Domain\TechCart.CartItems.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.4" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.*" />
  </ItemGroup>

</Project>
